### ISSUE TITLE
Invalid CSS in example

### ISSUE THREAD

**Issue by edub008** [wolfprint3d/RPM-Examples#1]
Hi guys, I'm a product manager with DeepMotion currently working on integrating RPM into our product.  I noticed there's some invalid CSS in the examples, looks like you are missing **px** when specifying width and height properties in both the `container` and the `content` css properties. 

See here for example: 
https://github.com/wolfprint3d/RPM-Examples/blob/master/examples/iframe.html#L8-L9

Need to just add px so it's "400px" for both width and height, otherwise it's invalid css.

**Comment by tiivik** [comment]
Thanks a lot! Fixed :)
